### ISSUE TITLE
"The chunksize parameter should be a number" while trying to use Rados storage for Registry

### ISSUE THREAD

**Issue by treed** [distribution/distribution#1162]
I'm trying to use the Rados storage backend for Registry with the latest "registry:2" image, pulled a few hours ago. (I haven't tried using prior images.) I get the following panic on startup:

```
panic: The chunksize parameter should be a number

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7fb9337892d8, 0xc208130030, 0xc20810e500, 0x7fb9337892d8)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:105 +0x3e1
github.com/docker/distribution/registry.NewRegistry(0x7fb933789318, 0xc208130030, 0xc20810e500, 0xc20810e500, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:94 +0x2d4
github.com/docker/distribution/registry.func·001(0x1299880, 0xc20802b570, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:57 +0x2d1
github.com/spf13/cobra.(*Command).execute(0x1299880, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x1299880, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x2a

goroutine 9 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [runnable]:
text/template/parse.lexText(0xc20806c100, 0xe317f0)
        /usr/src/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20806c100)
        /usr/src/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/src/go/src/text/template/parse/lex.go:191 +0x1ac
panic: The chunksize parameter should be a number

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7fba2dbf7848, 0xc2080ce030, 0xc20810e500, 0x7fba2dbf7848)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:105 +0x3e1
github.com/docker/distribution/registry.NewRegistry(0x7fba2dbf7888, 0xc2080ce030, 0xc20810e500, 0xc20810e500, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:94 +0x2d4
github.com/docker/distribution/registry.func·001(0x1299880, 0xc20802b570, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:57 +0x2d1
github.com/spf13/cobra.(*Command).execute(0x1299880, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x1299880, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x2a

goroutine 9 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [runnable]:
text/template/parse.lexText(0xc20806c100, 0xe317f0)
        /usr/src/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20806c100)
        /usr/src/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/src/go/src/text/template/parse/lex.go:191 +0x1ac
panic: The chunksize parameter should be a number

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7fd3647023c0, 0xc2080ce030, 0xc20810c500, 0x7fd3647023c0)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:105 +0x3e1
github.com/docker/distribution/registry.NewRegistry(0x7fd364702400, 0xc2080ce030, 0xc20810c500, 0xc20810c500, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:94 +0x2d4
github.com/docker/distribution/registry.func·001(0x1299880, 0xc20802b570, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:57 +0x2d1
github.com/spf13/cobra.(*Command).execute(0x1299880, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x1299880, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x2a

goroutine 9 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [runnable]:
text/template/parse.lexText(0xc20806c100, 0xe317f0)
        /usr/src/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20806c100)
        /usr/src/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/src/go/src/text/template/parse/lex.go:191 +0x1ac
panic: The chunksize parameter should be a number

goroutine 1 [running]:
github.com/docker/distribution/registry/handlers.NewApp(0x7f982588c4d0, 0xc2080d2030, 0xc20810e500, 0x7f982588c4d0)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:105 +0x3e1
github.com/docker/distribution/registry.NewRegistry(0x7f982588c510, 0xc2080d2030, 0xc20810e500, 0xc20810e500, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:94 +0x2d4
github.com/docker/distribution/registry.func·001(0x1299880, 0xc20802b570, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:57 +0x2d1
github.com/spf13/cobra.(*Command).execute(0x1299880, 0xc20800a010, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:495 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x1299880, 0x0, 0x0)
        /go/src/github.com/docker/distribution/Godeps/_workspace/src/github.com/spf13/cobra/command.go:560 +0x18d
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:22 +0x2a

goroutine 9 [syscall]:
os/signal.loop()
        /usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 10 [runnable]:
text/template/parse.lexText(0xc20806c100, 0xe317f0)
        /usr/src/go/src/text/template/parse/lex.go:228 +0x37b
text/template/parse.(*lexer).run(0xc20806c100)
        /usr/src/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/src/go/src/text/template/parse/lex.go:191 +0x1ac
```

The relevant part of the config is:

```
storage:
  rados:
    poolname: docker
    username: docker
    chunksize: 4194304
```

4194304 is a number, and this is indeed the line from the documentation for this section. (I guess, strictly speaking, I don't need to have this there since it's default, but this still looks like a bug.)

Also, I don't believe this should be a panic. It should just print a clean error message.

**Comment by RichardScothern** [comment]
@gierschv : yaml is decoding the `chunksize` (uint64) param into an `int` which is falling the typecast in go (even though they are the same width on my machine).

**Comment by treed** [comment]
I *can* verify that if I just let the value be its default, that works fine. (And is a suitable work around for me.)

**Comment by RichardScothern** [comment]
yep, it takes its default value from a const.  We should still fix it though :)

**Comment by milosgajdos** [comment]
Closing as `rados` driver is no longer supported by this project.
