### ISSUE TITLE
Cannot use S3 storage driver with Canada central region (ca-central-1)

### ISSUE THREAD

**Issue by adaphi** [distribution/distribution#2271]
Hey,

If you try and use the AWS region "ca-central-1" with registry 2.6.1 it panics:
```
panic: Invalid region provided: ca-central-1

goroutine 1 [running]:
panic(0xb7cb80, 0xc420422d20)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x10657c0, 0xc4203b2630, 0xc420372a80, 0x10657c0)
        /go/src/github.com/docker/distribution/registry/handlers/app.go:123 +0x3908
github.com/docker/distribution/registry.NewRegistry(0x7fec1fae8130, 0xc4203b2630, 0xc420372a80, 0xc420372a80, 0x0, 0x0)
        /go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108d140, 0xc420125c20, 0x1, 0x1)
        /go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108d140, 0xc420125bd0, 0x1, 0x1, 0x108d140, 0xc420125bd0)
        /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108d2e0, 0xc4201cdf40, 0xc4200001a0)
        /go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
        /go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d
```

I can see the region is validated in the code, and I can see the master branch has ca-central-1 available, but I guess this isn't in 2.6.1.

IRC suggests a further improvement might be necessary:
```
adaphi
Hello
3:00 pm
I'd like to run the registry with the S3 storage driver and a bucket in the canadian central aws region
3:00 pm
It doesn't seem like this is supported in the latest release
3:00 pm
but I can see it's been added to the storage driver code
3:00 pm
Is there a release target for this?
4:55 pm
h110hawk
adaphi: what do you mean it's not supported? don't you just specify a region in the config?
6:05 pm
adaphi
h110hawk: Yes, but it verifies the setting against a predefined list of valid regions. ca-central-1 is not in that list in the 2.6.1 source
6:06 pm
so it panics: "panic: Invalid region provided: ca-central-1"
6:30 pm
h110hawk
RIP
6:30 pm
The "correct" fix for that is to pull the region list from the API itself
6:30 pm
and validate that
6:31 pm
link the code where you see it's been fixed?
May 10th, 2017
10:24 am
adaphi
h110hawk: https://github.com/docker/distribution/blob/master/registry/storage/driver/s3-aws/s3.go#L121
```

Is support for this region due for release any time soon?

**Comment by dmcgowan** [comment]
The plan is within the next month. Until then you can run a build from master with `distribution/registry:master`, our master should be fairly stable since we are not merging in any large features before the release. Suggestion if you go this route, find a build which you validated as stable and push it to your own repository so you can pin the tag or run by digest.

**Comment by DWSR** [comment]
Any update on this? We're trying to spin up our own registry and still running into this issue when trying to run 2.6.2

**Comment by milosgajdos** [comment]
Closing as this is available in the latest release.
