### ISSUE TITLE
Registry panic when S3 ListObjects returns 500

### ISSUE THREAD

**Issue by andrew-leung** [distribution/distribution#2479]
We're running Docker Distribution 2.6.2, backed by S3. The registry was running on an AWS m3.large HVM instances running Ubuntu Trusty. The registry process was launched by running `/apps/docker-registry/bin/registry serve /apps/docker-registry/config.yml` and is fronted by nginx.

When we observed the panics, there were many outstanding ListObject calls happening (many upstream systems list a repo's /tags/list and call /v2/_catalog). Many of the registry goroutines panic'd at around the same time. For example, 37 different goroutines ListObjects panic'd during a 4 second window.

During this time, AWS S3 was having a confirmed issue that resulted in S3 ListBucket calls for certain prefix paths returning 500. This AWS issue lasted for several hours and in most cases, these 500s were properly returned back to the registry's caller. However, we found around 50 instances where these errors resulted in a registry panic. The backtrace looks like:

```
2017/12/18 03:09:38 http: panic serving 127.0.0.1:11268: &{0xc820010580 map[] 2017-12-18 03:09:38.215143737 +0000 UTC panic runtime error: invalid memory address or nil pointer dereference}
goroutine 284461955 [running]:
net/http.(*conn).serve.func1(0xc820614400)
        /mnt/builds/slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.6/src/net/http/server.go:1389 +0xc1
panic(0xde93e0, 0xc820775d40)
        /mnt/builds/slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.6/src/runtime/panic.go:426 +0x4e9
github.com/docker/distribution/vendor/github.com/Sirupsen/logrus.(*Entry).log(0xc820775d40, 0x0, 0xc820775d80, 0x40)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/vendor/github.com/Sirupsen/logrus/entry.go:103 +0x60f
github.com/docker/distribution/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc820775d40, 0xc821dac7e0, 0x1, 0x1)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/vendor/github.com/Sirupsen/logrus/entry.go:148 +0x7c
github.com/docker/distribution/vendor/github.com/Sirupsen/logrus.(*Logger).Panic(0xc820010580, 0xc821dac7e0, 0x1, 0x1)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/vendor/github.com/Sirupsen/logrus/logger.go:155 +0xed
github.com/docker/distribution/vendor/github.com/Sirupsen/logrus.Panic(0xc821dac7e0, 0x1, 0x1)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/vendor/github.com/Sirupsen/logrus/exported.go:102 +0x41
github.com/docker/distribution/registry.panicHandler.func1.1()
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/registry.go:297 +0x1a1
panic(0xcdd900, 0xc820018080)
        /mnt/builds/slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.6/src/runtime/panic.go:426 +0x4e9
github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).List(0xc82028db00, 0x7fb55ffe89d0, 0xc821d25c00, 0xc82402c9b0, 0x43, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:634 +0x76f
github.com/docker/distribution/registry/storage/driver/base.(*Base).List(0xc820392970, 0x7fb55ffe89d0, 0xc821d25c00, 0xc82402c9b0, 0x43, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/storage/driver/base/base.go:157 +0x327
github.com/docker/distribution/registry/storage.(*tagStore).All(0xc820e060f0, 0x7fb55ffea010, 0xc82002af60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/storage/tagstore.go:35 +0x22d
github.com/docker/distribution/registry/handlers.(*tagsHandler).GetTags(0xc82002af60, 0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/handlers/tags.go:39 +0x183
github.com/docker/distribution/registry/handlers.(*tagsHandler).GetTags-fm(0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/handlers/tags.go:20 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820e060e0, 0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.6/src/net/http/server.go:1618 +0x3a
github.com/docker/distribution/vendor/github.com/gorilla/handlers.MethodHandler.ServeHTTP(0xc8214c2420, 0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/vendor/github.com/gorilla/handlers/handlers.go:35 +0xb2
github.com/docker/distribution/registry/handlers.(*App).dispatcher.func1(0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/handlers/app.go:698 +0x27bc
net/http.HandlerFunc.ServeHTTP(0xc82038a960, 0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.6/src/net/http/server.go:1618 +0x3a
github.com/docker/distribution/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8201f1220, 0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/vendor/github.com/gorilla/mux/mux.go:98 +0x29e
github.com/docker/distribution/registry/handlers.(*App).ServeHTTP(0xc82039e120, 0x7fb56002f0c0, 0xc8208f44b0, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/handlers/app.go:616 +0x30e
github.com/docker/distribution/registry.alive.func1(0x7fb56002efa0, 0xc823b72e70, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/registry/registry.go:317 +0x131
net/http.HandlerFunc.ServeHTTP(0xc8203ba2a0, 0x7fb56002efa0, 0xc823b72e70, 0xc820fd10a0)
        /mnt/builds/slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.6/src/net/http/server.go:1618 +0x3a
github.com/docker/distribution/health.Handler.func1(0x7fb56002efa0, 0xc823b72e70, 0xc820fd10a0)
        /mnt/builds/slave/workspace/titus-registry/build/gobuild/build-docker-registry/stage/src/github.com/docker/distribution/health/health.go:271 +0x19a
net/http.HandlerFunc.ServeHTTP(0xc82038b940, 0x7fb56002efa0, 0xc823b72e70, 0xc820fd10a0)
        /mnt/builds/slave/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.6/src/net/http/server.go:1618 +0x3a
```

It appears that dereferencing the `resp` object caused the panic, though this happens after access to both `resp.Contents` and `resp.CommonPrefixes` and checking `if err != nil` when `resp` is returned. This may suggest a cancelled or incomplete response may be the cause.

**Comment by stevvooe** [comment]
@andrew-leung Thanks for the report!

The panic seems to be at https://github.com/docker/distribution/blob/v2.6.2/registry/storage/driver/s3-aws/s3.go#L634, when it de-references a boolean without checking for `nil`.

If you're willing to test and send a patch, let me know. If not, I'll take care of it.

**Comment by andrew-leung** [comment]
@stevvooe Thanks for looking into it. I don't have a great way to reproduce/verify a fix. I think it's better if you could take care of but can do it if that's not possible.

**Comment by milosgajdos** [comment]
Closing, fixed in https://github.com/distribution/distribution/pull/4412
