### ISSUE TITLE
swift storage driver requires credentials with unnecessary privileges

### ISSUE THREAD

**Issue by johnl** [distribution/distribution#2667]
the swift storage driver attempts to retrieve the account's temporary url secret key from the account metadata and aborts if the attempt is refused.

Not all credentials allow read access to the account metadata - some credentials can only access the container and its objects.

So using a set of lower privileged credentials like this is currently impossible with Distribution, and you're forced to use higher privileges than are really necessary.

```
panic: Failed to fetch account info (Operation forbidden)

goroutine 1 [running]:
panic(0xb7dbc0, 0xc420176380)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/distribution/registry/handlers.NewApp(0x1066800, 0xc420397980, 0xc42038aa80, 0x1066800)
	/go/src/github.com/docker/distribution/registry/handlers/app.go:123 +0x3908
github.com/docker/distribution/registry.NewRegistry(0x7feaf4099108, 0xc420397980, 0xc42038aa80, 0xc42038aa80, 0x0, 0x0)
	/go/src/github.com/docker/distribution/registry/registry.go:86 +0x213
github.com/docker/distribution/registry.glob..func1(0x108e180, 0xc420307ae0, 0x1, 0x1)
	/go/src/github.com/docker/distribution/registry/registry.go:55 +0x106
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).execute(0x108e180, 0xc420307a90, 0x1, 0x1, 0x108e180, 0xc420307a90)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:495 +0x190
github.com/docker/distribution/vendor/github.com/spf13/cobra.(*Command).Execute(0x108e320, 0xc4201aff40, 0xc4200001a0)
	/go/src/github.com/docker/distribution/vendor/github.com/spf13/cobra/command.go:560 +0x3c3
main.main()
	/go/src/github.com/docker/distribution/cmd/registry/main.go:24 +0x2d
```

```
$ registry --version
registry github.com/docker/distribution v2.6.2
```

**Comment by milosgajdos** [comment]
Closing as Swift driver has been deprecated in the latest release and is no longer supported.
