### ISSUE TITLE
registry panic error on getOutstandingUploads function

### ISSUE THREAD

**Issue by hernandanielg** [distribution/distribution#2908]
Hello I am running registry using docker image `registry:2.7.0` and I am getting the following error from time to time
```
2019-04-28T17:50:31.400869529Z panic: runtime error: index out of range
2019-04-28T17:50:31.400968253Z
2019-04-28T17:50:31.4009844Z goroutine 57 [running]:
2019-04-28T17:50:31.40099443Z github.com/docker/distribution/registry/storage.getOutstandingUploads.func1(0xeff780, 0xc003548180, 0xeff780, 0xc003548180)
2019-04-28T17:50:31.401003666Z  /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:73 +0x4bd
2019-04-28T17:50:31.401012499Z github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc0034e4400, 0xc00357b901, 0xc00061aac0)
2019-04-28T17:50:31.401020732Z  /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:1001 +0x776
2019-04-28T17:50:31.401029802Z github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc0001b80c8, 0x7f944571b298, 0xc0001e5b20, 0xc003144b90, 0xc000cd15a0, 0x0, 0x0, 0x0, 0x40, 0x40)
2019-04-28T17:50:31.401038822Z  /go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
2019-04-28T17:50:31.401074255Z github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc0001bce00, 0xefec00, 0xc0007db960, 0xc000cd1b58, 0xc000265ac0, 0x40, 0x0, 0x0, 0xc0001e0240, 0x0, ...)
2019-04-28T17:50:31.401082005Z  /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
2019-04-28T17:50:31.401088835Z github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk.func1(0xc0001c8e00, 0xc000c30501, 0xc00013a998)
2019-04-28T17:50:31.401095655Z  /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:1015 +0x889
2019-04-28T17:50:31.401108469Z github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).ListObjectsV2PagesWithContext(0xc0001b80c8, 0x7f944571b298, 0xc0007db960, 0xc000b81360, 0xc000cd1a98, 0x0, 0x0, 0x0, 0x1, 0x2)
2019-04-28T17:50:31.401116359Z  /go/src/github.com/docker/distribution/vendor/github.com/aws/aws-sdk-go/service/s3/api.go:4198 +0x111
2019-04-28T17:50:31.401123226Z github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).doWalk(0xc0001bce00, 0xefec00, 0xc0007db8f0, 0xc00013ab58, 0xc0007fcbd1, 0x2c, 0x0, 0x0, 0xc0001e0240, 0x0, ...)
2019-04-28T17:50:31.401130309Z  /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:971 +0x3a1
2019-04-28T17:50:31.401137188Z github.com/docker/distribution/registry/storage/driver/s3-aws.(*driver).Walk(0xc0001bce00, 0xefec00, 0xc0007db8f0, 0xc0003bdac0, 0x20, 0xc0001e0240, 0x2, 0x0)
2019-04-28T17:50:31.401144113Z  /go/src/github.com/docker/distribution/registry/storage/driver/s3-aws/s3.go:919 +0x160
2019-04-28T17:50:31.401151005Z github.com/docker/distribution/registry/storage/driver/base.(*Base).Walk(0xc0003a5d90, 0xefec00, 0xc0007db8f0, 0xc0003bdac0, 0x20, 0xc0001e0240, 0x0, 0x0)
2019-04-28T17:50:31.401158176Z  /go/src/github.com/docker/distribution/registry/storage/driver/base/base.go:239 +0x234
2019-04-28T17:50:31.401167858Z github.com/docker/distribution/registry/storage.getOutstandingUploads(0xefed40, 0xc000302c80, 0xf0a2c0, 0xc0003a5d90, 0x2, 0x0, 0x0, 0x0)
2019-04-28T17:50:31.401174938Z  /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:70 +0x236
2019-04-28T17:50:31.401181867Z github.com/docker/distribution/registry/storage.PurgeUploads(0xefed40, 0xc000302c80, 0xf0a2c0, 0xc0003a5d90, 0xbf2748e0865b9fb0, 0xfffddb3f4ea00701, 0x15a5680, 0x1, 0x0, 0x0, ...)
2019-04-28T17:50:31.401190854Z  /go/src/github.com/docker/distribution/registry/storage/purgeuploads.go:34 +0x163
2019-04-28T17:50:31.401229144Z github.com/docker/distribution/registry/handlers.startUploadPurger.func1(0xf0ddc0, 0xc00032e3c0, 0xefed40, 0xc000302c80, 0xf0a2c0, 0xc0003a5d90, 0x2260ff9290000, 0x0, 0x4e94914f0000)
2019-04-28T17:50:31.401260173Z  /go/src/github.com/docker/distribution/registry/handlers/app.go:1071 +0x221
2019-04-28T17:50:31.401269945Z created by github.com/docker/distribution/registry/handlers.startUploadPurger
2019-04-28T17:50:31.401278169Z  /go/src/github.com/docker/distribution/registry/handlers/app.go:1064 +0x2e9
```

We are using s3 bucket to store our images and the registry is running on k8s pods

I can share the config (with masked info) if needed

**Comment by hernandanielg** [comment]
I can see these errors in the log before the panic error
```
2019-04-28T17:50:30.209043211Z 10.111.167.151 - - [28/Apr/2019:17:50:30 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/17.12.1-ce go/go1.9.6 kernel/4.14.106-97.85.amzn2.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"

2019-04-28T17:50:30.209130103Z time="2019-04-28T17:50:30.20872178Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.11.2 http.request.host=our.registry.com http.request.id=53077115-0359-4e18-a39d-72ab687ba46f http.request.method=GET http.request.remoteaddr=10.22.82.78 http.request.uri="/v2/" http.request.useragent="docker/17.12.1-ce go/go1.9.6 kernel/4.14.106-97.85.amzn2.x86_64 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"
```
